# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "JupyterBook Tests"
author: Scott Henderson
logo: img/GeoSMART_logo.svg
only_build_toc_files: true

# Information about where the book exists on the web
repository:
  url: https://github.com/scottyhq/codeautolink # Online location of your book
  path_to_book: ./book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'force'

html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: "https://mybinder.org"

sphinx:
  extra_extensions:
    - sphinx_codeautolink
  config:
    codeautolink_concat_default: True
    codeautolink_warn_on_missing_inventory: True
    codeautolink_warn_on_failed_resolve: True
    codeautolink_inventory_map: {
            # temp workaround https://github.com/pydata/xarray/issues/4279
            "xarray.core.dataarray.DataArray.isel": "xarray.DataArray.isel",
            "xarray.core.dataarray.DataArray.mean": "xarray.DataArray.mean",
    }
    intersphinx_mapping:
      xarray:
        - https://docs.xarray.dev/en/latest/
        - null
      numpy:
        - https://numpy.org/doc/stable
        - null
      pandas:
        - https://pandas.pydata.org/pandas-docs/stable
        - null
      python:
        - https://docs.python.org/3/
        - null
